slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    map_update_interval: 0.3
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.1
    transform_timeout: 0.5
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 
    enable_interactive_mode: false
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    map_start_pose: [0.0, 0.0, 0.0]
    map_start_at_dock: true

